### ISSUE TITLE
特定条件時にプログラムが強制終了する

### ISSUE THREAD

**Issue by Heppokoyuki** [kapipara/possys#1]
## 操作内容
- Userを登録しないままNFCカード登録に進む
- NFCを登録する(登録出来るのも問題)
- 残高照会する(ここで強制終了)

## エラーメッセージ
![image](https://user-images.githubusercontent.com/26131632/43699550-3251cddc-998a-11e8-8016-369f268e75ca.png)

**Comment by kapipara** [comment]
1個目は、ユーザ名照合で弾きます。
2,3個目はそれで解決できるかも……。 そもそも1個目でNoneに対して照合しちゃってるのも問題になりそうなので直します。
ちなみに、ユーザ登録しないでNFCカード追加しようとしたときは、ユーザ名はどうしましたか？

**Comment by Heppokoyuki** [comment]
任意のものを入力しました。部内データベースのレコードを確認したところ、どうやらTestUserとして認識されている？

**Comment by kapipara** [comment]
Slackのログからそんな気がしていたが……
デバッグして……来週中にはどうにかします……

**Comment by Heppokoyuki** [comment]
頑張ってくださいw
